/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessConsoleIndexRouteImport } from './routes/sess/console/index'
import { Route as SessHomeIndexRouteImport } from './routes/sess/home/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessConsoleIndexRoute = SessConsoleIndexRouteImport.update({
  id: '/sess/console/',
  path: '/sess/console/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessHomeIndexRoute = SessHomeIndexRouteImport.update({
  id: '/sess/home/',
  path: '/sess/home/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sess/console/': typeof SessConsoleIndexRoute
  '/sess/home/': typeof SessHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sess/console': typeof SessConsoleIndexRoute
  '/sess/home': typeof SessHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sess/console/': typeof SessConsoleIndexRoute
  '/sess/home/': typeof SessHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sess/console/' | '/sess/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sess/console' | '/sess/home'
  id: '__root__' | '/' | '/sess/console/' | '/sess/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessConsoleIndexRoute: typeof SessConsoleIndexRoute
  SessHomeIndexRoute: typeof SessHomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sess/console/': {
      id: '/sess/console/'
      path: '/sess/console'
      fullPath: '/sess/console/'
      preLoaderRoute: typeof SessConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sess/home/': {
      id: '/sess/home/'
      path: '/sess/home'
      fullPath: '/sess/home/'
      preLoaderRoute: typeof SessHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessConsoleIndexRoute: SessConsoleIndexRoute,
  SessHomeIndexRoute: SessHomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
